### ISSUE TITLE
PV Integration

### ISSUE THREAD

**Issue by CR4567** [bosch-buderus-wp/bosch-buderus-wp.github.io#4]
Hi,
erstmal ein Kompliment und Dank für die großartige Idee, mal alle Informationen an einem Ort zu sammeln.
Wir sind seit September auch im Besitz der Bosch 6800 und ich bin seit dem am Foren durchforsten nach den passenden Einstellungen und Integrationen, speziell für HomeAssistant.
Tatsächlich habe ich es auch schon über den ESP integriert. 
Da wir auch im Besitz einer PV Anlage sind, kam nun auch die Idee auf, bei genügend PV Leistung mehr Warmwasser zu produzieren, etc.
Die Wärmepumpe unterstützt das ja theoretisch schon und besitzt dafür einen eigenen Eingang.

Hattest du dich mit dem Thema schon auseinandergesetzt oder Informationen dazu?

**Comment by Tihmann** [comment]
Hier gibt es ein paar Informationen https://bbqkees-electronics.nl/2024/10/03/using-the-smart-grid-sg-and-photovoltaic-pv-function-of-your-heat-pump-with-the-ems-gateways/

**Comment by CR4567** [comment]
ah danke für den Tip, damit könnte es tatsächlich klappen. Ich werde es am Wochenende testen und berichten.

**Comment by CR4567** [comment]
Noch nicht so viel wie ich wollte. 
Sagen kann ich aber schon mal, dass es tatsächlich funktioniert über das ems gateway den Wert zugehörigen Wert für PV oder SG einfach auf 1 zu setzen. Die Wärmepumpe zeigt dann im Display auch an, dass PV Strom aktiv ist.
Allerdings habe ich noch 3 Themen die ich mir genauer ansehen muss:
- Welche Werte machen in der WP Sinn bei aktivem PV Strom?
- Welcher Eingang lohnt sich eher für HA, der PV oder SG Eingang?
- Logik in HA wann Eingang auf aktiv wechselt und wann zurück

Sobald ich dazu mehr habe, gebe ich die Erfahrungen hier gerne weiter.

**Comment by Tihmann** [comment]
schau mal bei evcc https://evcc.io/ Da sind jetzt Wärmepumpen integriert, auch Buderus mit emsesp

**Comment by bosch-buderus-wp** [comment]
Hallo @Tihmann , vielen Dank für die Integration in evcc. Hab es heute getestet. Ich kenne mich aber noch nicht so gut mit evcc aus und bin daher nicht sicher, ob ich alles richtig gemacht habe. Daher hätte ich noch ein paar Fragen:

- Wenn ich in evcc die Wärmepumpe auf `PV` stelle, passiert gar nichts. Nur wenn ich `Min+PV` oder `Schnell` auswähle, wechselt `hpin4opt` auf `100000100000`.
- Ich habe im Service-Menü der Wärmepumpe unter `Anlageneinstellungen` &rarr; `Photovoltoikanlage` die `Erhöhung der Wunschtemp. beim Heizen` auf 2K eingestellt und `Erhöhter Warmwasserkomfort` eingeschaltet. Ersteres scheint zu funktionieren, aber bei `Erhöhter Warmwasserkomfort` sehe ich keinen Effekt. Hätte erwartet, dass "WWK gewählte Temperatur" (dhw.seltemp) bei PV-Überschuss auf die Komfort-Stopptemperatur erhöht wird.

Funktioniert das bei dir?

**Comment by bosch-buderus-wp** [comment]
Der zweite Punkt scheint doch wie erwartet zu funktionieren. Hab die falsche Entität angeschaut. "WWK Solltemperatur" ist jetzt auf der  Komfort-Stopptemperatur.

**Comment by thoughtgap** [comment]
Mir fehlt im Service Menü unter `Anlageneinstellungen` der Menüpunkt `Photovoltaikanlage`. Weißt du zufällig wo man den herzaubern kann? Unter `Anlageneinstellungen` → `Manuelle Inbetriebnahme` könnte man nur `Solar` oder `Energiemanager` aktivieren.
Compress CS6800iAW 12M Inneneinheit hier, mit Software 9.7.0 und 47.11-Field beim Bedienfeld.

**Comment by Tihmann** [comment]
Unter Anlageneinstellungen / Externer Eingang 4 / PV

**Comment by bosch-buderus-wp** [comment]
Hab angefangen, die Integration der Wärmepumpe in evcc zu beschreiben. Siehe https://bosch-buderus-wp.github.io/docs/smarthome/evcc. Falls ich was falsch verstanden habe, gerne melden.

**Comment by thoughtgap** [comment]
Ich setze die PV-Überschuss-Einstellung seit ein paar Tagen erfolgreich mit folgenden Automatisierungen direkt aus Home Assistant heraus. Ggf abweichende Sensor-Namen beachten:

```yaml
sequence:
  - target:
      entity_id: text.boiler_input_4_options
    data:
      value: >
        {% set current = states('text.boiler_input_4_options') %} {% if current
        | length > 0 %} 1{{ current[1:] }} {% else %} 1 {% endif %}
    action: text.set_value
alias: "Wärmepumpe: PV Überschuss an"
description: ""
```

```yaml
sequence:
  - target:
      entity_id: text.boiler_input_4_options
    data:
      value: >
        {% set current = states('text.boiler_input_4_options') %} {% if current
        | length > 0 %} 0{{ current[1:] }} {% else %} 0 {% endif %}
    action: text.set_value
alias: "Wärmepumpe: PV Überschuss aus"
description: ""
```
